FROM toposoid/scala-base:2.12.12

WORKDIR /app

ENV DEPLOYMENT=local

RUN apt-get update \
&& apt-get -y install git \
&& git clone https://github.com/toposoid/scala-common.git \
&& cd scala-common \
&& sbt publishLocal \
&& cd .. \
&& git clone https://github.com/toposoid/scala-data-accessor-neo4j.git


